"""
Page 4 — Download Report

Generates a PDF summary report for the selected watershed and offers
it as a Streamlit download button.
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import io
import os
import tempfile

from utils import load_well_index, render_sidebar, get_filtered_data, render_filter_summary
from openff_utils.chem_list_summary import ChemListSummary
from openff_utils.generate_PDF_report_v1 import PDFReport

st.set_page_config(page_title="Download Report", layout="wide")

well_index = load_well_index()
render_sidebar(well_index)

st.title("Download Report")

if "ws_chem" not in st.session_state:
    st.info("Select a location in the sidebar and click **Find Watershed**.")
    st.stop()

well_gb, ws_chem = get_filtered_data()
name: str = st.session_state["watershed_name"]
huc_scale: int = st.session_state["huc_scale"]
lat: float = st.session_state["search_lat"]
lon: float = st.session_state["search_lon"]

st.subheader(name)
n_chem = ws_chem["bgCAS"].nunique() if not ws_chem.empty else 0
st.caption(f"HUC{huc_scale} · {len(well_gb):,} disclosures · {n_chem} chemicals")
render_filter_summary()

if ws_chem.empty:
    st.warning("No data to report for this watershed.")
    st.stop()

if "in_std_filtered" not in ws_chem.columns:
    ws_chem = ws_chem.copy()
    ws_chem["in_std_filtered"] = True

if "date" not in ws_chem.columns:
    well_gb_raw = st.session_state.get("well_gb", pd.DataFrame())
    if not well_gb_raw.empty and "date" in well_gb_raw.columns:
        date_map = well_gb_raw[["DisclosureId", "date"]].drop_duplicates("DisclosureId")
        ws_chem = ws_chem.merge(date_map, on="DisclosureId", how="left")

if st.button("Generate PDF Report", type="primary"):
    with st.spinner("Building report..."):
        # Chemical summary
        chem_obj = ChemListSummary(ws_chem, summarize_by_chem=True,
                                   ignore_duplicates=True, use_remote=True)
        chem_table = chem_obj.get_display_table(colset="pdf_report1")

        # Water-use chart — save to a temp file for reportlab
        with tempfile.TemporaryDirectory() as tmpdir:
            water_img_path = os.path.join(tmpdir, "water_use.png")

            fig, ax = plt.subplots(figsize=(8, 3))
            ax.plot(well_gb["date"], well_gb["TotalBaseWaterVolume"],
                    "o", alpha=0.7, markersize=5)
            ax.set_title("Water Volume (gal) per Fracking Event")
            ax.set_ylabel("Gallons")
            ax.yaxis.set_major_formatter(
                plt.matplotlib.ticker.StrMethodFormatter("{x:,.0f}")
            )
            fig.tight_layout()
            fig.savefig(water_img_path, dpi=120)
            plt.close(fig)

            # Build PDF to a temp file then read into bytes
            pdf_path = os.path.join(tmpdir, "report.pdf")
            report_meta = {
                "Watershed Name": name,
                "HUC Scale": huc_scale,
                "Target Latitude": lat,
                "Target Longitude": lon,
                "Disclosures": len(well_gb),
                "Unique Chemicals": ws_chem["bgCAS"].nunique(),
            }

            report = PDFReport(pdf_path)
            report.build_title_page(
                report_name=f"Watershed Report: {name}",
                intro_paragraph=(
                    "This report summarizes chemicals disclosed in FracFocus for "
                    "fracking wells within the selected USGS watershed. "
                    "Generated by the Open-FF Watershed Chemical Explorer."
                ),
                meta_info=report_meta,
            )
            report.build_well_list(
                well_gb[["date", "OperatorName", "APINumber",
                         "WellName", "TotalBaseWaterVolume"]]
            )
            report.build_water_graphic(water_img_path)
            report.build_chemical_summary(chem_table)
            report.generate()

            with open(pdf_path, "rb") as f_pdf:
                pdf_bytes = f_pdf.read()

    safe_name = name.replace(" ", "_").replace("/", "-")[:50]
    st.download_button(
        label="Download PDF",
        data=pdf_bytes,
        file_name=f"watershed_report_{safe_name}.pdf",
        mime="application/pdf",
    )
    st.success("Report ready — click above to download.")
